"""
NacArtha Content Scheduler

Runs 24/7 on Railway.

  Monday    4 PM ET → run_long_pipeline()  — generate 10-min long video + cut all 7 weekly shorts
  Tue-Sun   4 PM ET → run_short_upload()   — upload today's pre-cut short from weekly_plan.json
  One-time  4 PM ET → run_trailer_upload() — post nacartha_trailer_final.mp4 to all 3 channels
  POST /fire?mode=long|short|trailer       — manual trigger (token-gated)
  POST /upload-trailer                     — receive trailer file from curl, save to /tmp
"""
import cgi
import logging
import os
import sys
import threading
from datetime import datetime, date
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).parent))

from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.cron import CronTrigger

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("scheduler")

NY_TZ      = ZoneInfo("America/New_York")
_ALL_LANGS = ["en", "hi", "te"]

_pipeline_lock  = threading.Lock()
_startup_time   = datetime.now()   # recorded at module load = container start time
_STARTUP_GUARD  = 300              # 5 minutes — never fire within this window of a deploy


def _mark_lang_done(lang: str):
    pass  # no-op — YouTube is source of truth, not local markers


def _deploy_guard() -> bool:
    """Returns True if we should skip (container just deployed)."""
    uptime_secs = (datetime.now() - _startup_time).total_seconds()
    if uptime_secs < _STARTUP_GUARD:
        log.warning(
            f"Cron fired {uptime_secs:.0f}s after container start — "
            f"deploy restart detected. SKIPPING. Next run at 4:00 PM ET."
        )
        return True
    return False


def run_long_pipeline():
    """Monday 4 PM ET — generate long video + cut all 7 weekly shorts."""
    if _deploy_guard():
        return
    log.info("=== Monday: Long video pipeline (4 PM ET) ===")
    if not _pipeline_lock.acquire(blocking=False):
        log.warning("Pipeline already running — skipping")
        return
    try:
        import sys as _sys
        _sys.modules.pop("nac_orchestrator", None)
        import nac_orchestrator
        nac_orchestrator.main(langs=_ALL_LANGS, on_lang_done=_mark_lang_done)
        log.info("=== Long pipeline complete ===")
        _telegram("✅ NacArtha long video + weekly shorts ready")
    except Exception as e:
        log.error(f"Long pipeline failed: {e}", exc_info=True)
        _telegram(f"❌ NacArtha long pipeline FAILED:\n`{e}`")
    finally:
        _pipeline_lock.release()


def run_short_upload():
    """Tue-Sun 4 PM ET — upload today's pre-cut short from weekly_plan.json."""
    if _deploy_guard():
        return
    if os.environ.get("SKIP_SHORTS_TODAY", "").lower() in ("1", "true", "yes"):
        log.warning("SKIP_SHORTS_TODAY is set — skipping short upload for today.")
        return
    log.info("=== Daily short upload (4 PM ET) ===")
    if not _pipeline_lock.acquire(blocking=False):
        log.warning("Pipeline already running — skipping")
        return
    try:
        import sys as _sys
        _sys.modules.pop("nac_orchestrator", None)
        import nac_orchestrator
        nac_orchestrator.main_short(langs=_ALL_LANGS, on_lang_done=_mark_lang_done)
        log.info("=== Short upload complete ===")
    except Exception as e:
        log.error(f"Short upload failed: {e}", exc_info=True)
        _telegram(f"❌ NacArtha short upload FAILED:\n`{e}`")
    finally:
        _pipeline_lock.release()


TRAILER_PATH = Path("/tmp/nac_trailer.mp4")

_PRIVACY_HTML = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Privacy Policy — NacArtha</title>
<style>body{font-family:sans-serif;max-width:760px;margin:60px auto;padding:0 24px;color:#222;line-height:1.7}h1{color:#0a0a0a}h2{margin-top:2em}a{color:#c9a84c}</style>
</head><body>
<h1>Privacy Policy</h1>
<p><strong>Last updated: June 2026</strong></p>
<p>This Privacy Policy describes how NacArtha AI Lab ("we", "us") handles information in connection with the NacArtha Content Engine application.</p>

<h2>1. Information We Collect</h2>
<p>The NacArtha Content Engine is an automated content publishing tool. It does not collect personal data from end users. The application processes only:</p>
<ul>
  <li>Platform OAuth tokens (stored securely as environment variables, never logged or shared)</li>
  <li>Video and image files generated by the NacArtha AI pipeline</li>
  <li>Metadata (titles, descriptions, tags) for published content</li>
</ul>

<h2>2. How We Use Information</h2>
<p>OAuth tokens are used solely to publish content to authorized social media accounts on behalf of the account owner. We do not sell, share, or transfer any data to third parties.</p>

<h2>3. TikTok Integration</h2>
<p>When connected to TikTok via the TikTok Content Posting API, this application uses the <code>video.publish</code> and <code>video.upload</code> scopes to upload pre-rendered educational videos. No TikTok user data is read, stored, or processed beyond what is required to confirm successful publication.</p>

<h2>4. Data Retention</h2>
<p>Video files are stored temporarily on the server during upload and deleted after successful publication. No user data is retained beyond the active session.</p>

<h2>5. Contact</h2>
<p>For privacy questions: <a href="mailto:nacarthaai@gmail.com">nacarthaai@gmail.com</a></p>
</body></html>"""

_TERMS_HTML = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Terms of Service — NacArtha</title>
<style>body{font-family:sans-serif;max-width:760px;margin:60px auto;padding:0 24px;color:#222;line-height:1.7}h1{color:#0a0a0a}h2{margin-top:2em}a{color:#c9a84c}</style>
</head><body>
<h1>Terms of Service</h1>
<p><strong>Last updated: June 2026</strong></p>
<p>By using the NacArtha Content Engine ("the Application"), you agree to these Terms of Service.</p>

<h2>1. Description</h2>
<p>NacArtha Content Engine is an AI-powered automated content creation and publishing platform that generates educational trading videos and publishes them to social media channels including TikTok, Instagram, and YouTube.</p>

<h2>2. Acceptable Use</h2>
<p>The Application is intended solely for use by authorised NacArtha account owners to publish original educational content. You agree not to use the Application to publish content that violates any platform's terms of service, applicable laws, or community guidelines.</p>

<h2>3. Third-Party Platforms</h2>
<p>Use of the Application in connection with TikTok, Instagram, or YouTube is subject to those platforms' own terms of service. We are not responsible for changes to third-party APIs or platform policies.</p>

<h2>4. Intellectual Property</h2>
<p>All content generated and published through the Application is owned by NacArtha AI Lab. The Application itself is proprietary software.</p>

<h2>5. Disclaimer</h2>
<p>Content published through this Application is educational in nature and does not constitute financial advice. Trading involves risk. Past performance is not indicative of future results.</p>

<h2>6. Contact</h2>
<p>For questions: <a href="mailto:nacarthaai@gmail.com">nacarthaai@gmail.com</a></p>
</body></html>"""

# Metadata for each channel — same video, localised titles
TRAILER_META = {
    "en": {
        "title":       "I Built an AI Trading Bot That Never Sleeps | NacArtha AI Lab",
        "description": (
            "Welcome to NacArtha AI Lab — where we build a fully automated AI trading system "
            "from scratch, live. Every day the system scans hundreds of stocks, identifies RSI "
            "and EMA crossover signals, and scores every trade before it happens. No emotions. "
            "Pure data.\n\n"
            "Paper trading now. Going live soon.\n\n"
            "#NacArtha #AITrading #AlgoTrading #StockMarket #QuantFinance"
        ),
        "tags": ["NacArtha", "AI trading", "algo trading", "stock market", "quant finance"],
    },
    "hi": {
        "title":       "AI ट्रेडिंग बॉट जो कभी नहीं सोता | NacArtha AI Lab",
        "description": (
            "NacArtha AI Lab में आपका स्वागत है — जहाँ हम एक पूरी तरह से स्वचालित AI ट्रेडिंग "
            "सिस्टम बना रहे हैं। हर दिन यह सिस्टम सैकड़ों स्टॉक स्कैन करता है और सिग्नल पहचानता है।\n\n"
            "#NacArtha #AITrading #AlgoTrading #शेयरबाजार"
        ),
        "tags": ["NacArtha", "AI trading", "algo trading", "share market", "quant"],
    },
    "te": {
        "title":       "నిద్రపోని AI ట్రేడింగ్ బాట్ | NacArtha AI Lab",
        "description": (
            "NacArtha AI Lab కి స్వాగతం — మేము పూర్తి స్వయంచాలక AI ట్రేడింగ్ సిస్టమ్ "
            "నిర్మిస్తున్నాము. రోజూ వందల స్టాక్‌లను స్కాన్ చేసి సిగ్నల్స్ గుర్తిస్తుంది.\n\n"
            "#NacArtha #AITrading #AlgoTrading #స్టాక్‌మార్కెట్"
        ),
        "tags": ["NacArtha", "AI trading", "algo trading", "stock market", "Telugu"],
    },
}


def _check_lipsync_providers():
    """Log HeyGen and ElevenLabs lip-sync capability for future use."""
    import requests as _req

    # ── HeyGen ────────────────────────────────────────────────────────────────
    # HeyGen supports lip-sync via /v2/video/generate with input_type=talking_photo
    # and audio_url — the avatar's lips move to the provided audio.
    heygen_key = os.environ.get("HEYGEN_API_KEY", "")
    if heygen_key:
        try:
            r = _req.get(
                "https://api.heygen.com/v2/avatars",
                headers={"x-api-key": heygen_key},
                timeout=10,
            )
            if r.status_code == 200:
                log.info("✓ HeyGen lip-sync AVAILABLE — use /v2/video/generate with audio_url to sync avatar lips to any audio")
            else:
                log.warning(f"HeyGen check: HTTP {r.status_code}")
        except Exception as e:
            log.warning(f"HeyGen check failed: {e}")
    else:
        log.info("HeyGen: HEYGEN_API_KEY not set — skipping check")

    # ── ElevenLabs ────────────────────────────────────────────────────────────
    # ElevenLabs does NOT offer video lip-sync — audio generation only.
    # For lip-sync use HeyGen with the ElevenLabs-generated audio as audio_url.
    log.info("ElevenLabs: audio-only, no native lip-sync. Workflow → ElevenLabs audio → HeyGen talking_photo with audio_url")


def run_trailer_upload():
    """One-time 4 PM ET — upload nacartha_trailer_final.mp4 to all 3 channels."""
    log.info("=== Trailer upload to 3 channels ===")
    if not TRAILER_PATH.exists():
        log.error(f"Trailer not found at {TRAILER_PATH}. Upload it first via POST /upload-trailer")
        _telegram("❌ Trailer upload FAILED — file not found. POST /upload-trailer first.")
        return
    if not _pipeline_lock.acquire(blocking=False):
        log.warning("Pipeline already running — skipping trailer upload")
        return
    try:
        _check_lipsync_providers()

        from config import settings
        from engines.upload_engine import UploadEngine

        uploader = UploadEngine(
            client_id=settings.YOUTUBE_CLIENT_ID,
            client_secret=settings.YOUTUBE_CLIENT_SECRET,
            refresh_tokens=settings.YOUTUBE_REFRESH_TOKENS,
        )
        results = uploader.upload_all_languages(
            video_path=TRAILER_PATH,
            thumbnail_path=Path("/tmp/nac_trailer_thumb.jpg") if Path("/tmp/nac_trailer_thumb.jpg").exists() else None,
            translations=TRAILER_META,
            topic_type="educational",
        )
        ok    = {lang: url for lang, url in results.items() if url}
        fails = [lang for lang, url in results.items() if not url]
        log.info(f"=== YouTube trailer upload done: {ok} ===")

        # ── Social platforms ──────────────────────────────────────────────────
        from engines.social_engine import SocialEngine
        social_caption = (
            "Hey! Nac here 👋 Welcome to NacArtha AI Lab — building a fully automated "
            "AI trading system from scratch, live.\n\n"
            "📊 500+ stocks scanned daily • 🤖 RSI + EMA signals • 📈 Going live soon\n\n"
            "Follow for updates! #NacArtha #AITrading #AlgoTrading #StockMarket"
        )
        social = SocialEngine()
        social_results = social.post_all(
            video_path=TRAILER_PATH,
            caption=social_caption,
            title=TRAILER_META["en"]["title"],
        )

        msg = "✅ Trailer posted!\n"
        msg += "\n".join(f"• [YT {l}] {u}" for l, u in ok.items())
        msg += "\n" + "\n".join(f"• [{p}] {u or 'skipped'}" for p, u in social_results.items())
        if fails:
            msg += f"\n⚠️ YT Failed: {fails}"
        _telegram(msg)
    except Exception as e:
        log.error(f"Trailer upload failed: {e}", exc_info=True)
        _telegram(f"❌ Trailer upload FAILED:\n`{e}`")
    finally:
        _pipeline_lock.release()


def _telegram(text: str):
    import requests
    token   = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
    if not token or not chat_id:
        return
    try:
        requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": text, "parse_mode": "Markdown"},
            timeout=10,
        )
    except Exception:
        pass


def _fire_pipeline(langs: list, mode: str = "long"):
    if not _pipeline_lock.acquire(blocking=False):
        log.warning("Pipeline already running — skipping manual fire")
        return
    try:
        import sys as _sys
        _sys.modules.pop("nac_orchestrator", None)
        import nac_orchestrator
        log.info(f"=== Manual fire: mode={mode} langs={langs} ===")
        if mode == "short":
            nac_orchestrator.main_short(langs=langs, on_lang_done=_mark_lang_done)
        elif mode == "trailer":
            _pipeline_lock.release()   # run_trailer_upload acquires its own lock
            run_trailer_upload()
            return
        else:
            nac_orchestrator.main(langs=langs, on_lang_done=_mark_lang_done)
        log.info("=== Manual fire complete ===")
    except Exception as e:
        log.error(f"Manual fire failed: {e}", exc_info=True)
        _telegram(f"❌ NacArtha manual fire FAILED:\n`{e}`")
    finally:
        if _pipeline_lock.locked():
            _pipeline_lock.release()


def _start_dashboard_server():
    """Status dashboard only — no trigger endpoint."""
    token     = os.environ.get("TRIGGER_TOKEN", "")
    html_path = Path(__file__).parent / "static" / "dashboard.html"
    _TIKTOK_META = '<meta name="tiktok-developers-site-verification" content="l2oXJEDKAviuUSqlwkxh54nyZIJlyxm4" />'
    if html_path.exists():
        raw = html_path.read_text().replace("%%TOKEN%%", token)
        # Inject TikTok verification meta tag into <head>
        _html = raw.replace("<head>", f"<head>\n  {_TIKTOK_META}", 1) if "<head>" in raw else f"<html><head>{_TIKTOK_META}</head><body>{raw}</body></html>"
    else:
        _html = f"<html><head>{_TIKTOK_META}</head><body><h1>NacArtha Scheduler Running</h1></body></html>"

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, fmt, *args):
            log.info(f"HTTP {fmt % args}")

        def do_GET(self):
            path = self.path.split("?")[0]
            if path in ("/", ""):
                body = _html.encode()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif path == "/tiktokl2oXJEDKAviuUSqlwkxh54nyZIJlyxm4.txt":
                body = b"tiktokl2oXJEDKAviuUSqlwkxh54nyZIJlyxm4.txt"
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif path in ("/health", "/healthz", "/ping"):
                body = b"ok"
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif path == "/privacy":
                body = _PRIVACY_HTML.encode()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif path == "/terms":
                body = _TERMS_HTML.encode()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            else:
                body = b"not found"
                self.send_response(404)
                self.send_header("Content-Type", "text/plain")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)

        def do_POST(self):
            from urllib.parse import urlparse, parse_qs
            parsed = urlparse(self.path)

            # ── Auth helper ───────────────────────────────────────────────────
            def _authed() -> bool:
                qs  = parse_qs(parsed.query)
                tok = qs.get("token", [""])[0]
                hdr = self.headers.get("x-token", "")
                return not token or tok == token or hdr == token

            if parsed.path == "/fire":
                if not _authed():
                    self._respond(403, b"unauthorized")
                    return
                qs          = parse_qs(parsed.query)
                langs_param = qs.get("langs", ["en,hi,te"])[0]
                mode        = qs.get("mode",  ["long"])[0]
                langs = [l.strip() for l in langs_param.split(",") if l.strip()]
                if _pipeline_lock.locked() and mode != "trailer":
                    self._respond(409, b"pipeline already running")
                else:
                    threading.Thread(
                        target=_fire_pipeline, args=(langs, mode), daemon=True
                    ).start()
                    self._respond(200, f"pipeline fired: mode={mode} langs={langs}".encode())

            elif parsed.path == "/upload-trailer":
                # Accept multipart file upload and save to TRAILER_PATH
                # Usage: curl -X POST .../upload-trailer \
                #              -F "file=@nacartha_trailer_final.mp4" \
                #              -H "x-token: nacartha"
                if not _authed():
                    self._respond(403, b"unauthorized")
                    return
                ctype = self.headers.get("Content-Type", "")
                length = int(self.headers.get("Content-Length", 0))
                if "multipart/form-data" in ctype:
                    form = cgi.FieldStorage(
                        fp=self.rfile,
                        headers=self.headers,
                        environ={"REQUEST_METHOD": "POST", "CONTENT_TYPE": ctype},
                    )
                    field = form.get("file") or form.get("video")
                    if field and field.file:
                        TRAILER_PATH.write_bytes(field.file.read())
                        size_mb = TRAILER_PATH.stat().st_size / 1024 / 1024
                        log.info(f"Trailer received: {size_mb:.1f} MB → {TRAILER_PATH}")
                        self._respond(200, f"trailer saved ({size_mb:.1f} MB). POST /fire?mode=trailer to upload now.".encode())
                    else:
                        self._respond(400, b"multipart field 'file' not found")
                elif length > 0:
                    # Raw body upload
                    data = self.rfile.read(length)
                    TRAILER_PATH.write_bytes(data)
                    size_mb = len(data) / 1024 / 1024
                    log.info(f"Trailer received (raw): {size_mb:.1f} MB → {TRAILER_PATH}")
                    self._respond(200, f"trailer saved ({size_mb:.1f} MB). POST /fire?mode=trailer to upload now.".encode())
                else:
                    self._respond(400, b"no file data received")

            else:
                self._respond(404, b"not found")

        def _respond(self, code: int, body: bytes):
            self.send_response(code)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

    port = int(os.environ.get("PORT", 8080))
    server = HTTPServer(("0.0.0.0", port), Handler)
    threading.Thread(target=server.serve_forever, daemon=True, name="Dashboard").start()
    log.info(f"Dashboard running on port {port} (read-only, no trigger)")


scheduler = BlockingScheduler()

# Monday 4 PM ET — full long video + cut 7 weekly shorts
scheduler.add_job(
    run_long_pipeline,
    CronTrigger(day_of_week="mon", hour=16, minute=0, timezone="America/New_York"),
    max_instances=1,
    misfire_grace_time=None,
)

# Tue-Sun 4 PM ET — upload today's pre-cut short
scheduler.add_job(
    run_short_upload,
    CronTrigger(day_of_week="tue,wed,thu,fri,sat,sun", hour=16, minute=0, timezone="America/New_York"),
    max_instances=1,
    misfire_grace_time=None,
)

_start_dashboard_server()

now_ny = datetime.now(NY_TZ)

# One-time trailer job — fires today at 4 PM ET if TRAILER_UPLOAD_DATE matches today
_trailer_date_env = os.environ.get("TRAILER_UPLOAD_DATE", "")   # e.g. "2026-06-16"
_today_str        = date.today().strftime("%Y-%m-%d")
if _trailer_date_env == _today_str:
    from apscheduler.triggers.date import DateTrigger
    _fire_at = datetime.now(NY_TZ).replace(hour=16, minute=0, second=0, microsecond=0)
    if _fire_at > datetime.now(NY_TZ):
        scheduler.add_job(
            run_trailer_upload,
            DateTrigger(run_date=_fire_at, timezone="America/New_York"),
            max_instances=1,
        )
        log.info(f"Trailer upload scheduled for {_fire_at.strftime('%Y-%m-%d %H:%M')} ET")
    else:
        log.warning(f"TRAILER_UPLOAD_DATE={_trailer_date_env} but 4PM ET already passed — trigger manually: POST /fire?mode=trailer&token=...")

log.info(f"NacArtha Scheduler — Mon 4PM=long video | Tue-Sun 4PM=daily short | Started {now_ny.strftime('%H:%M')} ET")
log.info("Manual: POST /fire?mode=long|short|trailer&token=... Missed jobs SKIPPED — no catch-up.")

try:
    scheduler.start()
except (KeyboardInterrupt, SystemExit):
    log.info("Scheduler stopped")
